const colors = {
  light: {
    text: '#111111',
    tint: '#FF416C',
    background: '#F5F5F7',
    foreground: '#111111',
    card: '#FFFFFF',
    cardForeground: '#111111',
    primary: '#FF416C',
    primaryForeground: '#FFFFFF',
    secondary: '#F0F0F0',
    secondaryForeground: '#333333',
    muted: '#F0F0F0',
    mutedForeground: '#9B9B9B',
    accent: '#F7941D',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#EBEBEB',
    input: '#F0F0F0',
    gradientStart: '#FF416C',
    gradientMid: '#FF4B2B',
    gradientEnd: '#F7941D',
    online: '#22C55E',
    unread: '#FF416C',
    tabBar: '#FFFFFF',
    tabBarBorder: '#EBEBEB',
    overlay: 'rgba(0,0,0,0.4)',
    skeletonBase: '#E8E8E8',
    skeletonHighlight: '#F5F5F5',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#FF416C',
    background: '#0E0E0E',
    foreground: '#FFFFFF',
    card: '#1C1C1E',
    cardForeground: '#FFFFFF',
    primary: '#FF416C',
    primaryForeground: '#FFFFFF',
    secondary: '#2C2C2E',
    secondaryForeground: '#EBEBEB',
    muted: '#2C2C2E',
    mutedForeground: '#8A8A8E',
    accent: '#F7941D',
    accentForeground: '#FFFFFF',
    destructive: '#FF453A',
    destructiveForeground: '#FFFFFF',
    border: '#2C2C2E',
    input: '#2C2C2E',
    gradientStart: '#FF416C',
    gradientMid: '#FF4B2B',
    gradientEnd: '#F7941D',
    online: '#30D158',
    unread: '#FF416C',
    tabBar: '#1C1C1E',
    tabBarBorder: '#2C2C2E',
    overlay: 'rgba(0,0,0,0.6)',
    skeletonBase: '#2C2C2E',
    skeletonHighlight: '#383838',
  },
  radius: 12,
};

export default colors;
