kind = "mobile"
previewPath = "/"
title = "Embr — Social Media"
version = "1.0.0"
id = "artifacts/embr"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 20050

[services.development]
run = "pnpm --filter @workspace/embr run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/embr", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/embr", "run", "serve" ]

[services.env]
PORT = "20050"
BASE_PATH = "/"
